#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$command = $argv[1] ?? 'serve';

switch ($command) {
    case 'serve':
        $host = $argv[2] ?? 'localhost:8000';
        echo "Starting development server on http://{$host}\n";
        shell_exec("php -S {$host} -t public");
        break;
        
    case 'install':
        echo "Installing dependencies...\n";
        shell_exec('composer install');
        break;
        
    default:
        echo "Unknown command: {$command}\n";
        echo "Available commands:\n";
        echo "  serve     Start the development server\n";
        echo "  install   Install dependencies\n";
        break;
}
